name: app

on:
    push:
        branches:
            - 'main'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   uses: actions/checkout@v2
            -   uses: bbonkr/get-version-action@v1.0.4
                id: get_version
                with:
                    project: "./package.json"

            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    push: true
                    tags: jefersonurbieta/exchange-office-app:${{ steps.get_version.outputs.version }}
